#!/bin/bash

# write-article.sh
# Writes the article (article.md) based on tasks.md, plan.md, and spec.md

set -e

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BLOGKIT_DIR="$REPO_ROOT/.blogkit"
TEMPLATES_DIR="$BLOGKIT_DIR/templates"

# Check prerequisites
PREREQ_OUTPUT=$(scripts/bash/check-prerequisites.sh --json --require-spec --require-plan --require-tasks)
FEATURE_DIR=$(echo "$PREREQ_OUTPUT" | grep -o '"FEATURE_DIR": "[^"]*"' | cut -d'"' -f4)
SPEC_FILE=$(echo "$PREREQ_OUTPUT" | grep -o '"SPEC_FILE": "[^"]*"' | cut -d'"' -f4)
PLAN_FILE=$(echo "$PREREQ_OUTPUT" | grep -o '"PLAN_FILE": "[^"]*"' | cut -d'"' -f4)
TASKS_FILE=$(echo "$PREREQ_OUTPUT" | grep -o '"TASKS_FILE": "[^"]*"' | cut -d'"' -f4)
ARTICLE_FILE="$FEATURE_DIR/article.md"

if [ -z "$FEATURE_DIR" ]; then
    echo "$PREREQ_OUTPUT"
    exit 1
fi

# Extract article title
ARTICLE_TITLE=$(grep "^# Article Specification:" "$SPEC_FILE" | sed 's/^# Article Specification: //' | head -1)
if [ -z "$ARTICLE_TITLE" ]; then
    ARTICLE_TITLE="Untitled Article"
fi

# Generate slug from title
SLUG=$(echo "$ARTICLE_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')

# Get current date
PUBLISH_DATE=$(date +%Y-%m-%d)

# Create article.md with frontmatter
# Note: The actual content should be generated by AI based on tasks.md, plan.md, and spec.md
# This script creates a basic structure that AI can fill in
cat > "$ARTICLE_FILE" <<EOF
---
title: "$ARTICLE_TITLE"
date: $PUBLISH_DATE
slug: $SLUG
tags: []
categories: []
excerpt: ""
---

# $ARTICLE_TITLE

<!-- This article will be generated based on tasks.md, plan.md, and spec.md -->
<!-- Use AI to generate content for each section defined in tasks.md -->

EOF

# Output JSON
cat <<EOF
{
  "FEATURE_DIR": "$FEATURE_DIR",
  "ARTICLE_FILE": "$ARTICLE_FILE",
  "ARTICLE_TITLE": "$ARTICLE_TITLE",
  "SLUG": "$SLUG"
}
EOF

echo ""
echo "Note: article.md has been created with basic structure."
echo "Use AI to generate content based on tasks.md, plan.md, and spec.md"

